# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-11 17:33
from __future__ import unicode_literals

import DjangoEasyScoping.ScopingMixin
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('widgets', '0005_auto_20180711_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(default=datetime.datetime.now)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widgets.Widget')),
            ],
            bases=(DjangoEasyScoping.ScopingMixin.ScopingMixin, models.Model),
        ),
    ]
