# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-11 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0005_auto_20180711_1733'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='items',
        ),
        migrations.AddField(
            model_name='purchase',
            name='items',
            field=models.ManyToManyField(to='widgets.Widget'),
        ),
    ]
