# Generated by Django 2.0.6 on 2018-07-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20180711_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='items',
            field=models.ManyToManyField(blank=True, to='widgets.Widget'),
        ),
    ]
