# Generated by Django 2.0.6 on 2018-07-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_auto_20180711_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='profit',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='sale_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
