# Generated by Django 2.0.6 on 2018-06-26 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('color', models.CharField(choices=[(1, 'Black'), (2, 'Blue'), (3, 'Brown'), (4, 'Green'), (5, 'Orange'), (6, 'Red'), (7, 'Red Orange'), (8, 'Sky Blue'), (9, 'Violet'), (10, 'White'), (11, 'Yellow'), (12, 'Yellow Green')], max_length=30)),
                ('size', models.CharField(choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large'), (4, 'Extra Large')], max_length=30)),
                ('shape', models.CharField(choices=[(1, 'Rectangle'), (2, 'Ellipse'), (3, 'Diamond'), (4, 'Trapezoid'), (5, 'Parallelogram'), (6, 'Triangle')], max_length=30)),
                ('used_on', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
