# Generated by Django 2.0.6 on 2018-07-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('blue', 'Blue'), ('brown', 'Brown'), ('green', 'Green'), ('orange', 'Orange'), ('red', 'Red'), ('red_orange', 'Red Orange'), ('sky_blue', 'Sky Blue'), ('violet', 'Violet'), ('white', 'White'), ('yellow', 'Yellow'), ('yellow_green', 'Yellow Green')], max_length=30),
        ),
        migrations.AlterField(
            model_name='widget',
            name='shape',
            field=models.CharField(choices=[('rectangle', 'Rectangle'), ('ellipse', 'Ellipse'), ('diamond', 'Diamond'), ('trapezoid', 'Trapezoid'), ('parallelogram', 'Parallelogram'), ('triangle', 'Triangle'), ('circle', 'Circle')], max_length=30),
        ),
        migrations.AlterField(
            model_name='widget',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('extra_large', 'Extra Large')], max_length=30),
        ),
    ]
