# Generated by Django 2.0.6 on 2018-07-11 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0002_auto_20180709_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='used_on',
        ),
    ]
