# Generated by Django 2.0.6 on 2018-07-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0003_remove_widget_used_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='widget',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
